# Generated by Django 4.2.4 on 2023-08-15 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_overpassfiredata_overpasspolicedata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OverpassFireData',
        ),
        migrations.DeleteModel(
            name='OverpassPoliceData',
        ),
    ]
