# Generated by Django 4.2.4 on 2023-08-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_overpassfiredata_overpasspolicedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overpassfiredata',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='overpasspolicedata',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
