# Generated by Django 4.2.4 on 2023-08-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_overpassfiredata_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overpassfiredata',
            name='amenity',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='overpasspolicedata',
            name='amenity',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
